In [1]:
import pennylane as qml
import torch
import numpy as np
import random
import torch.nn as nn
from tqdm import tqdm

In [2]:
import functools
import inspect
import math
from collections.abc import Iterable
from typing import Callable, Dict, Union, Any

from pennylane.qnode import QNode

try:
    import torch
    from torch.nn import Module

    TORCH_IMPORTED = True
except ImportError:
    # The following allows this module to be imported even if PyTorch is not installed. Users
    # will instead see an ImportError when instantiating the TorchLayer.
    from unittest.mock import Mock

    Module = Mock
    TORCH_IMPORTED = False


class TorchLayer(Module):
    def __init__(self,qnode,weights):
        if not TORCH_IMPORTED:
            raise ImportError(
                "TorchLayer requires PyTorch. PyTorch can be installed using:\n"
                "pip install torch\nAlternatively, "
                "visit https://pytorch.org/get-started/locally/ for detailed "
                "instructions."
            )
        super().__init__()

        #weight_shapes = {
        #    weight: (tuple(size) if isinstance(size, Iterable) else () if size == 1 else (size,))
        #    for weight, size in weight_shapes.items()
        #}

        # validate the QNode signature, and convert to a Torch QNode.
        # TODO: update the docstring regarding changes to restrictions when tape mode is default.
        #self._signature_validation(qnode, weight_shapes)
        self.qnode = qnode
        self.qnode.interface = "torch"

        self.qnode_weights = weights

    def forward(self, inputs):  # pylint: disable=arguments-differ
        """Evaluates a forward pass through the QNode based upon input data and the initialized
        weights.

        Args:
            inputs (tensor): data to be processed

        Returns:
            tensor: output data
        """

        if len(inputs.shape) > 1:
            # If the input size is not 1-dimensional, unstack the input along its first dimension,
            # recursively call the forward pass on each of the yielded tensors, and then stack the
            # outputs back into the correct shape
            reconstructor = [self.forward(x) for x in torch.unbind(inputs)]
            return torch.stack(reconstructor)

        # If the input is 1-dimensional, calculate the forward pass as usual
        return self._evaluate_qnode(inputs)


    def _evaluate_qnode(self, x):
        """Evaluates the QNode for a single input datapoint.

        Args:
            x (tensor): the datapoint

        Returns:
            tensor: output datapoint
        """
        kwargs = {
            **{self.input_arg: x},
            **{arg: weight.to(x) for arg, weight in self.qnode_weights.items()},
        }
        res = self.qnode(**kwargs)

        if isinstance(res, torch.Tensor):
            return res.type(x.dtype)

        return torch.hstack(res).type(x.dtype)

    def __str__(self):
        detail = "<Quantum Torch Layer: func={}>"
        return detail.format(self.qnode.func.__name__)

    __repr__ = __str__
    _input_arg = "inputs"

    @property
    def input_arg(self):
        """Name of the argument to be used as the input to the Torch layer. Set to ``"inputs"``."""
        return self._input_arg

In [188]:
class QSAL_pennylane(torch.nn.Module):
    def __init__(self,S,n,Denc,D):
        super().__init__()
        self.seq_num=S
        self.init_params_Q=torch.nn.Parameter(torch.stack([(np.pi/4) * (2 * torch.randn(n*(D+2)) - 1) for _ in range(self.seq_num)]))
        self.init_params_K=torch.nn.Parameter(torch.stack([(np.pi/4) * (2 * torch.randn(n*(D+2)) - 1) for _ in range(self.seq_num)]))
        self.init_params_V=torch.nn.Parameter(torch.stack([(np.pi/4) * (2 * torch.randn(n*(D+2)) - 1) for _ in range(self.seq_num)]))
        self.num_q=n
        self.Denc=Denc
        self.D=D
        self.d=n*(Denc+2)
        self.dev = qml.device("default.qubit", wires=self.num_q)
        
        self.vqnod=qml.QNode(self.circuit_v, self.dev, interface="torch")
        self.qnod=qml.QNode(self.circuit_qk, self.dev, interface="torch")
        self.weight_v = [{"weights": self.init_params_V[i]} for i in range(self.seq_num)]
        self.weight_q = [{"weights": self.init_params_Q[i]} for i in range(self.seq_num)]
        self.weight_k = [{"weights": self.init_params_K[i]} for i in range(self.seq_num)]
        #self.v_linear ={} #[qml.qnn.TorchLayer(self.vqnod[i], self.weight_shapes) for i in range(self.seq_num)]
        #for i in range(self.seq_num):
        self.v_linear = [TorchLayer(self.vqnod, self.weight_v[i]) for i in range(self.seq_num)]
        self.q_linear = [TorchLayer(self.qnod, self.weight_q[i]) for i in range(self.seq_num)]
        self.k_linear = [TorchLayer(self.qnod, self.weight_k[i]) for i in range(self.seq_num)]
        #self.qqnod=[qml.QNode(self.circuit_qk, self.dev, interface="torch") for i in range(self.seq_num)]

    def random_op(self):
        a=random.randint(0, 4)
        if a==0:
            op=qml.Identity(0)
        elif a==1:
            op=qml.PauliX(0)
        elif a==2:
            op=qml.PauliY(0)
        else:
            op=qml.PauliZ(0)

        op_elimated=qml.Identity(0)
        for i in range(1,self.num_q):
            op_elimated=op_elimated@qml.Identity(i)
        Select_wrong=True
        while Select_wrong:
            for i in range(1,self.num_q):
                a=random.randint(0, 4)
                if a==0:
                    op=op@qml.Identity(i)
                elif a==1:
                    op=op@qml.PauliX(i)
                elif a==2:
                    op=op@qml.PauliY(i)
                else:
                    op=op@qml.PauliZ(i)
            if op!=op_elimated:
                Select_wrong=False
        return op

    def circuit_v(self,inputs,weights):
            op=self.random_op()
            # feature_map
            indx=0
            for j in range(self.num_q):
                qml.RX(inputs[indx],j)
                qml.RY(inputs[indx+1],j)
                indx+=2
            for i in range(self.Denc):
                for j in range(self.num_q):
                    qml.CNOT(wires=(j,(j+1)%self.num_q))

                for j in range(self.num_q):
                    qml.RY(inputs[indx],j)
                    indx+=1
            # Ansatz
            indx=0
            for j in range(self.num_q):
                qml.RX(weights[indx],j)
                qml.RY(weights[indx+1],j)
                indx+=2
            for i in range(self.D):
                for j in range(self.num_q):
                    qml.CNOT(wires=(j,(j+1)%self.num_q))
                    
                for j in range(self.num_q):
                    #qc.rx(params[indx],j)
                    qml.RY(weights[indx],j)
                    indx+=1
            return [qml.expval(op) for i in range(self.d)] 

    def circuit_qk(self,inputs,weights):
        op=self.random_op()
        # feature_map
        indx=0
        for j in range(self.num_q):
            qml.RX(inputs[indx],j)
            qml.RY(inputs[indx+1],j)
            indx+=2
        for i in range(self.Denc):
            for j in range(self.num_q):
                qml.CNOT(wires=(j,(j+1)%self.num_q))

            for j in range(self.num_q):
                qml.RY(inputs[indx],j)
                indx+=1
        # Ansatz
        indx=0
        for j in range(self.num_q):
            qml.RX(weights[indx],j)
            qml.RY(weights[indx+1],j)
            indx+=2
        for i in range(self.D):
            for j in range(self.num_q):
                qml.CNOT(wires=(j,(j+1)%self.num_q))
                
            for j in range(self.num_q):
                #qc.rx(params[indx],j)
                qml.RY(weights[indx],j)
                indx+=1
        return [qml.expval(qml.PauliZ(0))]

    def forward(self,input):

        Q_output=torch.stack([self.q_linear[i](input[:,i]) for i in range(self.seq_num)])
        K_output=torch.stack([self.k_linear[i](input[:,i]) for i in range(self.seq_num)])
        V_output=torch.stack([self.v_linear[i](input[:,i]) for i in range(self.seq_num)])
        
        batch_size=len(input)
        Q_output=Q_output.transpose(0,2).repeat((self.seq_num,1,1))
        K_output=K_output.transpose(0,2).repeat((self.seq_num,1,1)).transpose(0,2)
        #print(V_output.size())
        #Q_grid, K_grid=torch.meshgrid(Q_output, K_output, indexing='ij')
        alpha=torch.exp(-(Q_output-K_output)**2)
        alpha=alpha.transpose(0,1)
        V_output=V_output.transpose(0,1)
        output=[]

        for i in range(self.seq_num):
            
            Sum_a=torch.sum(alpha[:,i,:],-1)
            div_sum_a=(1/Sum_a).repeat(self.d,self.seq_num,1).transpose(0,2)
            
            Sum_w=torch.sum(alpha[:,:,i].repeat((self.d,1,1)).transpose(0,2).transpose(0,1)*V_output*div_sum_a,1)
            output.append(Sum_w)
        return input+torch.stack(output).transpose(0,1)

class QSANN_pennylane(torch.nn.Module):
    def __init__(self,S,n,Denc,D,num_layers):
        """
        # input: input data
        # weight: trainable parameter
        # n: # of of qubits
        # d: embedding dimension which is equal to n(Denc+2)
        # Denc: the # number of layers for encoding 
        # D: the # of layers of variational layers
        # type "K": key, "Q": Query, "V": value
        """
        super().__init__()
        self.qsal_lst=[QSAL_pennylane(S,n,Denc,D) for _ in range(num_layers)]
        self.qnn=nn.Sequential(*self.qsal_lst)

    def forward(self,input):

        return self.qnn(input)

class QSANN_text_classifier(torch.nn.Module):
    def __init__(self,S,n,Denc,D,num_layers):
        """
        # input: input data
        # weight: trainable parameter
        # n: # of of qubits
        # d: embedding dimension which is equal to n(Denc+2)
        # Denc: the # number of layers for encoding 
        # D: the # of layers of variational layers
        # type "K": key, "Q": Query, "V": value
        """
        super().__init__()
        self.Qnn=QSANN_pennylane(S,n,Denc,D,num_layers)
        self.final_layer=nn.Linear(n*(Denc+2)*S, 10)
        self.final_layer=self.final_layer.float()

    def forward(self,input):

        x=self.Qnn(input)
        x=torch.flatten(x, start_dim=1)
        
        return self.final_layer(x)

# Multiclass Classification with Sklearn Image Dataset

# Sklearn Image Dataset (Patches prepared Row-wise)

In [240]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
digits = load_digits()
X, y = digits.images[0:200], digits.target[0:200]
X_train, X_test, y_train, y_test = train_test_split(X, y)

#train_mask = np.isin(y_train, [1, 7])
#X_train, y_train = X_train[train_mask], y_train[train_mask]

#test_mask = np.isin(y_test, [1, 7])
#X_test, y_test = X_test[test_mask], y_test[test_mask]

X_train = X_train.reshape(X_train.shape[0], 4, 16)
X_test = X_test.reshape(X_test.shape[0], 4, 16)

In [241]:
from keras.utils import to_categorical

In [242]:
y_train

array([5, 3, 7, 1, 2, 2, 3, 5, 5, 7, 6, 3, 2, 0, 8, 4, 8, 5, 3, 4, 0, 7,
       0, 9, 6, 6, 3, 4, 1, 9, 0, 6, 5, 5, 8, 7, 8, 7, 7, 5, 1, 9, 8, 8,
       8, 3, 2, 5, 0, 0, 0, 2, 6, 6, 3, 1, 1, 2, 6, 8, 3, 8, 8, 4, 8, 4,
       3, 0, 9, 9, 3, 9, 9, 7, 0, 4, 3, 9, 9, 0, 6, 1, 5, 4, 0, 5, 3, 2,
       8, 6, 8, 1, 9, 0, 6, 1, 3, 2, 4, 6, 6, 2, 3, 6, 6, 3, 8, 1, 9, 6,
       6, 5, 2, 1, 6, 9, 7, 2, 1, 9, 5, 0, 2, 9, 0, 1, 1, 3, 4, 7, 0, 0,
       0, 4, 9, 8, 4, 1, 2, 4, 3, 8, 5, 2, 0, 9, 8, 0, 6, 7])

In [243]:
y_train = to_categorical(y_train)

In [245]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)

In [234]:
y_test = to_categorical(y_test)

In [227]:
model=QSANN_text_classifier(4, 4, 2, 1, 1)

# seq * (num_qubits) * (num_layers + 2)

In [228]:
model

QSANN_text_classifier(
  (Qnn): QSANN_pennylane(
    (qnn): Sequential(
      (0): QSAL_pennylane()
    )
  )
  (final_layer): Linear(in_features=64, out_features=10, bias=True)
)

In [229]:
optimizer = torch.optim.Adam(lr=0.001, params=model.parameters())

In [230]:
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(trainable_params)

794


In [231]:
criterion = torch.nn.CrossEntropyLoss()

In [232]:
def multi_accuracy(preds, y):
    """
    Returns accuracy per batch, i.e. if you get 8/10 right, this returns 0.8, NOT 8
    """
    pred_soft = torch.log_softmax(preds, dim=1)
    _, pred_index = torch.max(pred_soft, dim=1)
    print(pred_index)
    y = [int(w.argmax()) for w in y]
    y = torch.tensor(y, dtype=float)
    print(y)
    correct_pred = (pred_index == y).float()
    #round predictions to the closest integer
    
    acc = correct_pred.sum()/len(correct_pred)

    return acc

In [233]:
for iepoch in tqdm(range(100)):
    optimizer.zero_grad()
    X_tensor=torch.tensor(X_train)
    predictions=model(X_tensor.float()).squeeze(1)
    #predictions=torch.sign(predictions)
    #print(predictions)
    label=torch.tensor(y_train)
    #for i in range(len(label)):
    #    if label[i]==1:
    #        label[i] = 0
    #    else:
    #        label[i]=1
    #print(label)
    loss = criterion(predictions, label.float())
    acc = multi_accuracy(predictions, label)
    print('')
    print('Accuracy:',acc)
    print('')
    print(loss)
    loss.backward()
    optimizer.step()

  0%|          | 0/100 [00:00<?, ?it/s]

tensor([8, 7, 3, 4, 3, 8, 3, 3, 3, 3, 3, 8, 3, 3, 8, 3, 7, 3, 8, 3, 8, 3, 8, 3,
        8, 4, 3, 3, 8, 3, 7, 8, 7, 3, 7, 3, 7, 3, 3, 8, 3, 3, 3, 3, 8, 7, 8, 3,
        3, 4, 8, 5, 5, 7, 3, 3, 5, 3, 8, 3, 8, 8, 3, 7, 3, 3, 3, 3, 8, 3, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2133)

tensor(7.0260, grad_fn=<DivBackward1>)


  1%|          | 1/100 [00:29<49:18, 29.89s/it]

tensor([8, 7, 3, 4, 3, 8, 3, 3, 3, 3, 3, 8, 3, 3, 8, 3, 7, 7, 8, 3, 8, 3, 8, 3,
        8, 4, 3, 3, 4, 3, 7, 8, 7, 3, 7, 3, 7, 3, 7, 8, 3, 3, 3, 3, 8, 7, 8, 7,
        7, 4, 8, 5, 5, 7, 3, 3, 5, 3, 8, 3, 8, 8, 3, 7, 3, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2267)

tensor(6.6618, grad_fn=<DivBackward1>)


  2%|▏         | 2/100 [01:01<50:25, 30.88s/it]

tensor([8, 7, 3, 4, 3, 8, 3, 3, 3, 3, 3, 8, 3, 3, 8, 3, 7, 7, 8, 3, 8, 3, 8, 3,
        8, 4, 3, 3, 4, 3, 7, 4, 7, 3, 7, 3, 7, 3, 7, 8, 3, 3, 3, 3, 8, 7, 8, 7,
        7, 4, 8, 5, 5, 7, 0, 3, 5, 3, 8, 3, 8, 8, 3, 7, 3, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2400)

tensor(6.3275, grad_fn=<DivBackward1>)


  3%|▎         | 3/100 [01:33<50:42, 31.36s/it]

tensor([4, 7, 3, 4, 3, 8, 3, 3, 3, 3, 3, 8, 3, 3, 8, 3, 7, 7, 8, 5, 8, 3, 8, 3,
        8, 4, 3, 3, 4, 3, 7, 4, 7, 3, 7, 3, 5, 3, 9, 8, 3, 3, 3, 3, 8, 7, 8, 7,
        7, 4, 8, 5, 5, 7, 0, 3, 5, 3, 8, 3, 8, 8, 3, 7, 3, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2400)

tensor(5.9787, grad_fn=<DivBackward1>)


  4%|▍         | 4/100 [02:06<51:04, 31.92s/it]

tensor([4, 7, 3, 4, 3, 8, 3, 3, 3, 3, 3, 8, 3, 3, 8, 7, 7, 7, 8, 5, 8, 3, 8, 3,
        8, 4, 3, 1, 4, 3, 7, 4, 7, 3, 7, 3, 7, 3, 9, 8, 3, 3, 3, 3, 8, 7, 7, 7,
        7, 4, 8, 5, 5, 7, 0, 3, 5, 3, 8, 3, 8, 8, 3, 7, 3, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2133)

tensor(5.6753, grad_fn=<DivBackward1>)


  5%|▌         | 5/100 [02:39<51:17, 32.40s/it]

tensor([4, 7, 3, 4, 3, 8, 3, 3, 3, 3, 3, 8, 3, 3, 8, 7, 7, 7, 4, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 4, 3, 7, 4, 7, 3, 7, 3, 5, 3, 9, 8, 3, 3, 3, 5, 8, 7, 1, 7,
        7, 4, 8, 5, 5, 7, 0, 7, 5, 3, 8, 3, 8, 8, 3, 7, 3, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2133)

tensor(5.3767, grad_fn=<DivBackward1>)


  6%|▌         | 6/100 [03:12<51:14, 32.71s/it]

tensor([4, 7, 3, 4, 3, 8, 3, 3, 3, 3, 0, 2, 3, 3, 8, 7, 7, 7, 1, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 0, 3, 7, 4, 7, 3, 7, 3, 5, 2, 9, 8, 4, 3, 3, 5, 8, 7, 1, 7,
        7, 4, 8, 5, 5, 7, 0, 3, 5, 2, 8, 3, 8, 8, 3, 7, 1, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2133)

tensor(5.1169, grad_fn=<DivBackward1>)


  7%|▋         | 7/100 [03:45<50:37, 32.66s/it]

tensor([4, 7, 3, 4, 3, 8, 3, 3, 3, 7, 0, 2, 3, 3, 8, 7, 7, 7, 1, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 0, 3, 9, 4, 7, 3, 7, 3, 5, 2, 9, 5, 4, 3, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 7, 5, 2, 8, 3, 8, 8, 3, 7, 1, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2133)

tensor(4.8635, grad_fn=<DivBackward1>)


  8%|▊         | 8/100 [04:18<50:19, 32.82s/it]

tensor([4, 7, 3, 0, 3, 2, 3, 3, 3, 1, 0, 2, 3, 3, 8, 7, 4, 7, 1, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 0, 3, 9, 4, 7, 8, 7, 3, 5, 2, 9, 5, 4, 3, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 0, 5, 2, 8, 3, 8, 8, 3, 9, 1, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2533)

tensor(4.6371, grad_fn=<DivBackward1>)


  9%|▉         | 9/100 [04:50<49:36, 32.71s/it]

tensor([4, 9, 3, 0, 3, 2, 3, 3, 5, 1, 1, 2, 3, 0, 8, 7, 7, 7, 1, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 0, 3, 9, 4, 7, 8, 7, 3, 5, 2, 9, 5, 7, 5, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 2, 5, 2, 8, 5, 8, 8, 3, 9, 1, 3, 3, 3, 8, 4, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2533)

tensor(4.4340, grad_fn=<DivBackward1>)


 10%|█         | 10/100 [05:24<49:26, 32.96s/it]

tensor([4, 9, 2, 0, 1, 2, 3, 3, 5, 1, 1, 2, 3, 0, 8, 7, 7, 7, 1, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 0, 3, 9, 4, 7, 8, 7, 3, 5, 2, 9, 5, 4, 5, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 2, 5, 2, 8, 5, 7, 8, 3, 9, 1, 3, 5, 3, 8, 1, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2267)

tensor(4.2571, grad_fn=<DivBackward1>)


 11%|█         | 11/100 [05:59<49:43, 33.52s/it]

tensor([4, 9, 2, 0, 1, 2, 3, 3, 5, 1, 1, 2, 3, 0, 8, 7, 7, 7, 1, 5, 8, 3, 8, 3,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 8, 7, 3, 5, 2, 9, 5, 7, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 2, 5, 2, 8, 5, 7, 8, 3, 9, 1, 3, 5, 3, 8, 1, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2267)

tensor(4.0897, grad_fn=<DivBackward1>)


 12%|█▏        | 12/100 [06:32<49:14, 33.58s/it]

tensor([4, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 8, 7, 4, 7, 1, 5, 4, 3, 8, 3,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 7, 7, 3, 5, 2, 9, 5, 7, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 2, 5, 2, 8, 5, 7, 8, 3, 9, 1, 3, 5, 3, 0, 1, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2267)

tensor(3.9421, grad_fn=<DivBackward1>)


 13%|█▎        | 13/100 [07:04<47:58, 33.09s/it]

tensor([4, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 7, 7, 7, 7, 1, 5, 4, 3, 2, 1,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 1, 7, 3, 5, 2, 9, 5, 7, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 8, 5, 5, 7, 0, 2, 5, 2, 0, 5, 7, 8, 3, 9, 1, 3, 5, 3, 0, 1, 8, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2267)

tensor(3.8036, grad_fn=<DivBackward1>)


 14%|█▍        | 14/100 [07:39<47:54, 33.43s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 7, 7, 7, 7, 1, 5, 4, 9, 2, 1,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 7, 7, 3, 0, 2, 9, 0, 7, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 5, 2, 0, 0, 7, 8, 3, 9, 1, 3, 5, 3, 0, 1, 7, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2667)

tensor(3.6702, grad_fn=<DivBackward1>)


 15%|█▌        | 15/100 [08:12<47:20, 33.42s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 7, 7, 4, 7, 7, 5, 4, 9, 2, 1,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 1, 7, 3, 0, 2, 9, 0, 7, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 5, 2, 0, 0, 7, 0, 3, 9, 1, 3, 5, 3, 0, 1, 6, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2800)

tensor(3.5341, grad_fn=<DivBackward1>)


 16%|█▌        | 16/100 [08:44<46:19, 33.09s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 7, 7, 7, 7, 7, 5, 4, 9, 2, 1,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 7, 7, 3, 0, 2, 9, 0, 7, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 5, 2, 0, 0, 7, 0, 3, 9, 1, 3, 5, 0, 0, 1, 6, 8,
        5, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.2667)

tensor(3.4152, grad_fn=<DivBackward1>)


 17%|█▋        | 17/100 [09:20<46:42, 33.76s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 7, 7, 4, 7, 7, 5, 4, 9, 2, 1,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 1, 7, 3, 0, 2, 7, 0, 9, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 5, 2, 0, 0, 7, 0, 3, 9, 1, 3, 1, 0, 0, 1, 6, 8,
        1, 5, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3067)

tensor(3.2940, grad_fn=<DivBackward1>)


 18%|█▊        | 18/100 [09:54<46:29, 34.02s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 7, 7, 4, 7, 7, 0, 4, 9, 2, 1,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 1, 7, 3, 0, 2, 7, 0, 9, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 0, 2, 0, 0, 7, 0, 3, 9, 1, 3, 1, 0, 0, 1, 6, 8,
        1, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3333)

tensor(3.1803, grad_fn=<DivBackward1>)


 19%|█▉        | 19/100 [10:30<46:33, 34.49s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 6, 7, 4, 7, 7, 0, 4, 9, 2, 1,
        0, 0, 3, 1, 0, 0, 9, 4, 9, 7, 7, 3, 9, 2, 7, 0, 9, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 0, 2, 0, 0, 7, 0, 3, 9, 1, 3, 1, 0, 0, 1, 6, 8,
        1, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3200)

tensor(3.0745, grad_fn=<DivBackward1>)


 20%|██        | 20/100 [11:05<46:07, 34.59s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 5, 1, 1, 2, 3, 0, 6, 7, 4, 7, 7, 0, 4, 9, 2, 0,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 7, 7, 3, 9, 2, 7, 0, 9, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 0, 2, 0, 0, 7, 0, 3, 9, 1, 3, 1, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3200)

tensor(2.9585, grad_fn=<DivBackward1>)


 21%|██        | 21/100 [11:40<45:58, 34.92s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 6, 1, 1, 2, 3, 0, 6, 7, 4, 7, 7, 0, 4, 9, 2, 0,
        1, 0, 3, 1, 0, 0, 9, 4, 9, 7, 7, 3, 9, 2, 7, 0, 9, 0, 3, 5, 8, 7, 1, 7,
        1, 4, 0, 5, 5, 7, 0, 2, 9, 2, 0, 0, 7, 0, 3, 9, 1, 6, 5, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3333)

tensor(2.8543, grad_fn=<DivBackward1>)


 22%|██▏       | 22/100 [12:14<44:49, 34.48s/it]

tensor([2, 9, 2, 0, 0, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 7, 4, 7, 7, 0, 4, 9, 2, 0,
        0, 0, 3, 1, 0, 0, 7, 4, 9, 7, 7, 3, 9, 2, 7, 0, 9, 0, 3, 5, 8, 7, 1, 6,
        1, 4, 0, 5, 5, 7, 0, 2, 9, 2, 0, 0, 7, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3600)

tensor(2.7451, grad_fn=<DivBackward1>)


 23%|██▎       | 23/100 [12:46<43:19, 33.76s/it]

tensor([4, 9, 2, 0, 0, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 7, 4, 7, 7, 0, 4, 9, 2, 0,
        1, 0, 3, 1, 0, 0, 7, 4, 9, 7, 7, 3, 9, 0, 7, 0, 9, 0, 6, 5, 8, 7, 1, 6,
        1, 4, 0, 5, 5, 7, 0, 2, 9, 2, 0, 0, 7, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3733)

tensor(2.6281, grad_fn=<DivBackward1>)


 24%|██▍       | 24/100 [13:18<42:14, 33.35s/it]

tensor([4, 9, 2, 0, 0, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 7, 4, 7, 7, 0, 4, 9, 2, 0,
        1, 0, 3, 1, 0, 0, 7, 4, 9, 7, 7, 3, 9, 0, 7, 0, 9, 0, 6, 5, 8, 7, 1, 6,
        1, 4, 0, 5, 5, 7, 0, 2, 9, 2, 0, 0, 7, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.3733)

tensor(2.5332, grad_fn=<DivBackward1>)


 25%|██▌       | 25/100 [13:52<41:44, 33.40s/it]

tensor([4, 9, 2, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 7, 4, 7, 7, 0, 4, 9, 2, 0,
        0, 0, 3, 1, 0, 0, 7, 4, 9, 7, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 1, 6,
        1, 4, 0, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4133)

tensor(2.4320, grad_fn=<DivBackward1>)


 26%|██▌       | 26/100 [14:25<41:10, 33.38s/it]

tensor([4, 9, 2, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 7, 7, 0, 4, 9, 2, 0,
        0, 0, 3, 1, 0, 0, 7, 4, 9, 7, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 1, 6,
        1, 4, 0, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4133)

tensor(2.3295, grad_fn=<DivBackward1>)


 27%|██▋       | 27/100 [15:00<41:13, 33.89s/it]

tensor([4, 9, 2, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 7, 7, 0, 4, 9, 2, 0,
        0, 0, 3, 1, 0, 0, 7, 4, 9, 7, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 6, 6,
        1, 4, 0, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4133)

tensor(2.2479, grad_fn=<DivBackward1>)


 28%|██▊       | 28/100 [15:35<40:57, 34.13s/it]

tensor([4, 9, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 4, 9, 2, 0,
        0, 0, 3, 1, 0, 0, 7, 4, 9, 8, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 6, 6,
        1, 4, 0, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 0, 3, 9, 1, 6, 9, 0, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4400)

tensor(2.1528, grad_fn=<DivBackward1>)


 29%|██▉       | 29/100 [16:10<40:48, 34.48s/it]

tensor([4, 9, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 4, 9, 8, 0,
        1, 0, 3, 1, 0, 0, 7, 4, 9, 8, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 6, 6,
        1, 4, 0, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 0, 3, 9, 1, 6, 9, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4400)

tensor(2.0720, grad_fn=<DivBackward1>)


 30%|███       | 30/100 [16:45<40:21, 34.59s/it]

tensor([0, 9, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 6, 9, 8, 0,
        1, 0, 3, 1, 0, 0, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 6, 6,
        1, 4, 0, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 0, 3, 9, 1, 6, 9, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4800)

tensor(1.9825, grad_fn=<DivBackward1>)


 31%|███       | 31/100 [17:18<39:21, 34.23s/it]

tensor([0, 9, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 6, 9, 8, 0,
        1, 0, 3, 1, 0, 0, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 6, 6,
        1, 4, 6, 9, 5, 7, 0, 2, 9, 2, 0, 0, 4, 8, 3, 9, 1, 6, 9, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.4933)

tensor(1.9026, grad_fn=<DivBackward1>)


 32%|███▏      | 32/100 [17:52<38:39, 34.12s/it]

tensor([0, 9, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 6, 9, 8, 0,
        1, 0, 3, 1, 0, 0, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 6, 5, 8, 7, 6, 6,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 2, 0, 0, 4, 8, 3, 1, 6, 5, 9, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.5333)

tensor(1.8218, grad_fn=<DivBackward1>)


 33%|███▎      | 33/100 [18:27<38:17, 34.28s/it]

tensor([0, 9, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 6, 9, 8, 0,
        1, 0, 3, 1, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 3, 3, 8, 7, 6, 6,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 2, 6, 0, 4, 8, 3, 1, 1, 5, 9, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.5600)

tensor(1.7585, grad_fn=<DivBackward1>)


 34%|███▍      | 34/100 [19:02<38:02, 34.59s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 5, 7, 0, 6, 9, 8, 6,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 3, 5, 8, 7, 6, 6,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 2, 6, 0, 4, 8, 3, 1, 6, 5, 9, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.5467)

tensor(1.6860, grad_fn=<DivBackward1>)


 35%|███▌      | 35/100 [19:38<37:41, 34.80s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 4, 7, 0, 6, 9, 8, 6,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 6,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 6, 5, 3, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6133)

tensor(1.6248, grad_fn=<DivBackward1>)


 36%|███▌      | 36/100 [20:10<36:15, 33.99s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 6, 6, 4, 5, 7, 0, 6, 9, 8, 6,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 6, 5, 3, 3, 0, 1, 6, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6133)

tensor(1.5610, grad_fn=<DivBackward1>)


 37%|███▋      | 37/100 [20:44<35:46, 34.07s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 7, 6, 4, 5, 7, 0, 6, 9, 8, 6,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 6, 5, 3, 3, 6, 1, 7, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6533)

tensor(1.5028, grad_fn=<DivBackward1>)


 38%|███▊      | 38/100 [21:19<35:30, 34.36s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 6, 5, 3, 3, 6, 1, 7, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6667)

tensor(1.4447, grad_fn=<DivBackward1>)


 39%|███▉      | 39/100 [21:53<34:55, 34.36s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 7, 8, 4, 5, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 6, 5, 3, 3, 6, 1, 7, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6667)

tensor(1.3811, grad_fn=<DivBackward1>)


 40%|████      | 40/100 [22:27<34:17, 34.30s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 6, 5, 3, 3, 6, 1, 7, 8,
        5, 9, 8])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6667)

tensor(1.3273, grad_fn=<DivBackward1>)


 41%|████      | 41/100 [23:02<33:51, 34.44s/it]

tensor([0, 1, 6, 0, 6, 2, 3, 3, 6, 1, 1, 2, 3, 1, 7, 8, 4, 5, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        5, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.6667)

tensor(1.2769, grad_fn=<DivBackward1>)


 42%|████▏     | 42/100 [23:36<33:03, 34.19s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7333)

tensor(1.2263, grad_fn=<DivBackward1>)


 43%|████▎     | 43/100 [24:08<32:01, 33.71s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 8, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7333)

tensor(1.1801, grad_fn=<DivBackward1>)


 44%|████▍     | 44/100 [24:41<31:04, 33.29s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 8, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7333)

tensor(1.1303, grad_fn=<DivBackward1>)


 45%|████▌     | 45/100 [25:14<30:22, 33.14s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 8, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7333)

tensor(1.0902, grad_fn=<DivBackward1>)


 46%|████▌     | 46/100 [25:48<30:14, 33.60s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 8, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7200)

tensor(1.0529, grad_fn=<DivBackward1>)


 47%|████▋     | 47/100 [26:21<29:28, 33.36s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 8, 0, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7467)

tensor(1.0153, grad_fn=<DivBackward1>)


 48%|████▊     | 48/100 [26:56<29:24, 33.94s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7600)

tensor(0.9754, grad_fn=<DivBackward1>)


 49%|████▉     | 49/100 [27:31<28:59, 34.10s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 8, 8,
        1, 0, 3, 2, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7333)

tensor(0.9465, grad_fn=<DivBackward1>)


 50%|█████     | 50/100 [28:05<28:30, 34.20s/it]

tensor([0, 1, 0, 0, 3, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 0, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7867)

tensor(0.9044, grad_fn=<DivBackward1>)


 51%|█████     | 51/100 [28:40<28:09, 34.48s/it]

tensor([0, 1, 0, 0, 6, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 8, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 0, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.7600)

tensor(0.8762, grad_fn=<DivBackward1>)


 52%|█████▏    | 52/100 [29:14<27:20, 34.18s/it]

tensor([0, 1, 0, 0, 3, 2, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 0, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8000)

tensor(0.8387, grad_fn=<DivBackward1>)


 53%|█████▎    | 53/100 [29:46<26:23, 33.69s/it]

tensor([0, 1, 0, 0, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 2, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8133)

tensor(0.8185, grad_fn=<DivBackward1>)


 54%|█████▍    | 54/100 [30:21<26:00, 33.92s/it]

tensor([0, 1, 0, 0, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 2, 3, 2, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8133)

tensor(0.7918, grad_fn=<DivBackward1>)


 55%|█████▌    | 55/100 [30:54<25:13, 33.64s/it]

tensor([0, 1, 0, 0, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8267)

tensor(0.7579, grad_fn=<DivBackward1>)


 56%|█████▌    | 56/100 [31:28<24:41, 33.67s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        1, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8400)

tensor(0.7319, grad_fn=<DivBackward1>)


 57%|█████▋    | 57/100 [32:02<24:13, 33.79s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8533)

tensor(0.7080, grad_fn=<DivBackward1>)


 58%|█████▊    | 58/100 [32:35<23:29, 33.56s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8533)

tensor(0.6795, grad_fn=<DivBackward1>)


 59%|█████▉    | 59/100 [33:09<23:03, 33.74s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8533)

tensor(0.6580, grad_fn=<DivBackward1>)


 60%|██████    | 60/100 [33:42<22:25, 33.63s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8533)

tensor(0.6375, grad_fn=<DivBackward1>)


 61%|██████    | 61/100 [34:15<21:40, 33.34s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8533)

tensor(0.6148, grad_fn=<DivBackward1>)


 62%|██████▏   | 62/100 [34:49<21:17, 33.61s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 3, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8533)

tensor(0.5975, grad_fn=<DivBackward1>)


 63%|██████▎   | 63/100 [35:22<20:36, 33.43s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 8, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8667)

tensor(0.5772, grad_fn=<DivBackward1>)


 64%|██████▍   | 64/100 [35:56<20:06, 33.51s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8800)

tensor(0.5586, grad_fn=<DivBackward1>)


 65%|██████▌   | 65/100 [36:31<19:47, 33.94s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 1, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8800)

tensor(0.5412, grad_fn=<DivBackward1>)


 66%|██████▌   | 66/100 [37:03<18:58, 33.49s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8933)

tensor(0.5266, grad_fn=<DivBackward1>)


 67%|██████▋   | 67/100 [37:35<18:06, 32.93s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 2, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.8933)

tensor(0.5078, grad_fn=<DivBackward1>)


 68%|██████▊   | 68/100 [38:08<17:33, 32.93s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4914, grad_fn=<DivBackward1>)


 69%|██████▉   | 69/100 [38:40<16:53, 32.71s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4797, grad_fn=<DivBackward1>)


 70%|███████   | 70/100 [39:12<16:19, 32.64s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4650, grad_fn=<DivBackward1>)


 71%|███████   | 71/100 [39:46<15:51, 32.81s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4500, grad_fn=<DivBackward1>)


 72%|███████▏  | 72/100 [40:18<15:17, 32.76s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4381, grad_fn=<DivBackward1>)


 73%|███████▎  | 73/100 [40:53<14:58, 33.27s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4263, grad_fn=<DivBackward1>)


 74%|███████▍  | 74/100 [41:25<14:16, 32.93s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4152, grad_fn=<DivBackward1>)


 75%|███████▌  | 75/100 [41:58<13:44, 33.00s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.4007, grad_fn=<DivBackward1>)


 76%|███████▌  | 76/100 [42:31<13:08, 32.86s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.3930, grad_fn=<DivBackward1>)


 77%|███████▋  | 77/100 [43:05<12:47, 33.36s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9200)

tensor(0.3801, grad_fn=<DivBackward1>)


 78%|███████▊  | 78/100 [43:40<12:24, 33.83s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 8,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9067)

tensor(0.3716, grad_fn=<DivBackward1>)


 79%|███████▉  | 79/100 [44:14<11:52, 33.95s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9333)

tensor(0.3638, grad_fn=<DivBackward1>)


 80%|████████  | 80/100 [44:47<11:10, 33.51s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 8, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9333)

tensor(0.3501, grad_fn=<DivBackward1>)


 81%|████████  | 81/100 [45:19<10:28, 33.10s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9333)

tensor(0.3463, grad_fn=<DivBackward1>)


 82%|████████▏ | 82/100 [45:52<09:57, 33.21s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 6, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9333)

tensor(0.3346, grad_fn=<DivBackward1>)


 83%|████████▎ | 83/100 [46:25<09:20, 33.00s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9467)

tensor(0.3219, grad_fn=<DivBackward1>)


 84%|████████▍ | 84/100 [46:57<08:42, 32.63s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9467)

tensor(0.3143, grad_fn=<DivBackward1>)


 85%|████████▌ | 85/100 [47:29<08:08, 32.58s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9467)

tensor(0.3091, grad_fn=<DivBackward1>)


 86%|████████▌ | 86/100 [48:02<07:37, 32.67s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 2, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9467)

tensor(0.2988, grad_fn=<DivBackward1>)


 87%|████████▋ | 87/100 [48:35<07:05, 32.70s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2901, grad_fn=<DivBackward1>)


 88%|████████▊ | 88/100 [49:08<06:35, 32.93s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2823, grad_fn=<DivBackward1>)


 89%|████████▉ | 89/100 [49:41<06:00, 32.81s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2762, grad_fn=<DivBackward1>)


 90%|█████████ | 90/100 [50:13<05:27, 32.79s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2698, grad_fn=<DivBackward1>)


 91%|█████████ | 91/100 [50:47<04:56, 32.99s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2649, grad_fn=<DivBackward1>)


 92%|█████████▏| 92/100 [51:20<04:23, 32.94s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2542, grad_fn=<DivBackward1>)


 93%|█████████▎| 93/100 [51:53<03:52, 33.15s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2449, grad_fn=<DivBackward1>)


 94%|█████████▍| 94/100 [52:27<03:20, 33.37s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2404, grad_fn=<DivBackward1>)


 95%|█████████▌| 95/100 [53:01<02:48, 33.61s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2333, grad_fn=<DivBackward1>)


 96%|█████████▌| 96/100 [53:35<02:14, 33.65s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2288, grad_fn=<DivBackward1>)


 97%|█████████▋| 97/100 [54:09<01:40, 33.60s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2241, grad_fn=<DivBackward1>)


 98%|█████████▊| 98/100 [54:42<01:07, 33.55s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2170, grad_fn=<DivBackward1>)


 99%|█████████▉| 99/100 [55:16<00:33, 33.54s/it]

tensor([0, 1, 0, 2, 3, 0, 3, 3, 0, 1, 1, 0, 3, 1, 7, 5, 4, 4, 7, 0, 6, 9, 0, 5,
        6, 2, 3, 8, 2, 3, 7, 4, 1, 8, 7, 3, 9, 0, 7, 0, 9, 9, 5, 3, 6, 7, 8, 5,
        1, 4, 6, 9, 9, 7, 0, 1, 9, 0, 6, 0, 4, 6, 3, 1, 8, 5, 3, 2, 6, 2, 7, 8,
        9, 9, 6])
tensor([0., 1., 0., 2., 3., 0., 3., 3., 0., 1., 1., 0., 3., 1., 7., 5., 4., 4.,
        7., 0., 6., 9., 0., 5., 6., 2., 3., 8., 2., 2., 7., 4., 1., 8., 7., 3.,
        5., 0., 7., 0., 9., 9., 5., 3., 6., 7., 8., 5., 1., 4., 6., 9., 9., 7.,
        2., 1., 9., 0., 6., 0., 4., 6., 3., 1., 8., 5., 3., 2., 6., 2., 7., 8.,
        9., 9., 6.], dtype=torch.float64)

Accuracy: tensor(0.9600)

tensor(0.2096, grad_fn=<DivBackward1>)


100%|██████████| 100/100 [55:49<00:00, 33.50s/it]


In [236]:
X_tensor=torch.tensor(X_test)
predictions=model(X_tensor.float()).squeeze(1)
label=torch.tensor(y_test)

loss = criterion(predictions, label.float())
acc = multi_accuracy(predictions, label.float())
print('')
print('Accuracy:',acc)
print('')
print(loss)

tensor([2, 6, 5, 5, 4, 5, 3, 1, 8, 7, 3, 9, 1, 6, 5, 2, 5, 7, 4, 8, 6, 3, 6, 1,
        2])
tensor([8., 1., 4., 5., 4., 2., 3., 1., 8., 7., 3., 9., 1., 6., 5., 2., 5., 7.,
        4., 8., 6., 3., 6., 1., 2.], dtype=torch.float64)

Accuracy: tensor(0.8400)

tensor(0.6853, grad_fn=<DivBackward1>)


# Sklearn Image Dataset (Patches Prepared Column-wise)

In [83]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
digits = load_digits()
X, y = digits.images[0:500], digits.target[0:500]
X_train, X_test, y_train, y_test = train_test_split(X, y)

train_mask = np.isin(y_train, [1, 7])
X_train, y_train = X_train[train_mask], y_train[train_mask]

test_mask = np.isin(y_test, [1, 7])
X_test, y_test = X_test[test_mask], y_test[test_mask]

#X_train = X_train.reshape(X_train.shape[0], 4, 16)
#X_test = X_test.reshape(X_test.shape[0], 4, 16)
X_train_c = X_train.transpose(0, 2, 1)
X_test_c = X_test.transpose(0, 2, 1)

X_train_c = X_train_c.reshape(X_train.shape[0], 4, 16)
X_test_c = X_test_c.reshape(X_test.shape[0], 4, 16)

In [79]:
model=QSANN_text_classifier(4,4,2,1,1)
optimizer = torch.optim.Adam(lr=0.01, params=model.parameters())
criterion = torch.nn.CrossEntropyLoss()

In [81]:
for iepoch in tqdm(range(10)):
    optimizer.zero_grad()
    X_tensor=torch.tensor(X_train_c)
    predictions=model(X_tensor.float()).squeeze(1)
    #predictions=torch.sign(predictions)
    #print(predictions)
    label=torch.tensor(y_train)
    for i in range(len(label)):
        if label[i]==1:
            label[i] = 0
        else:
            label[i]=1
    #print(label)
    loss = criterion(predictions, label.float())
    acc = binary_accuracy(predictions, label)
    print('')
    print('Accuracy:',acc)
    print('')
    print(loss)
    loss.backward()
    optimizer.step()


  0%|          | 0/10 [00:00<?, ?it/s]


Accuracy: tensor(0.9481)

tensor(146.3840, grad_fn=<DivBackward1>)



 10%|█         | 1/10 [00:24<03:43, 24.87s/it]


Accuracy: tensor(0.9481)

tensor(145.6917, grad_fn=<DivBackward1>)



 20%|██        | 2/10 [00:50<03:21, 25.24s/it]


Accuracy: tensor(0.9740)

tensor(143.9053, grad_fn=<DivBackward1>)



 30%|███       | 3/10 [01:15<02:56, 25.27s/it]


Accuracy: tensor(1.)

tensor(142.9731, grad_fn=<DivBackward1>)



 40%|████      | 4/10 [01:41<02:32, 25.37s/it]


Accuracy: tensor(0.9740)

tensor(142.8075, grad_fn=<DivBackward1>)



 50%|█████     | 5/10 [02:06<02:07, 25.52s/it]


Accuracy: tensor(0.9740)

tensor(142.7293, grad_fn=<DivBackward1>)



 60%|██████    | 6/10 [02:33<01:42, 25.74s/it]


Accuracy: tensor(0.9870)

tensor(142.6147, grad_fn=<DivBackward1>)



 70%|███████   | 7/10 [02:59<01:17, 25.88s/it]


Accuracy: tensor(0.9870)

tensor(142.3875, grad_fn=<DivBackward1>)



 80%|████████  | 8/10 [03:28<00:53, 26.82s/it]


Accuracy: tensor(0.9870)

tensor(142.2015, grad_fn=<DivBackward1>)



 90%|█████████ | 9/10 [03:53<00:26, 26.36s/it]


Accuracy: tensor(1.)

tensor(142.0063, grad_fn=<DivBackward1>)


100%|██████████| 10/10 [04:19<00:00, 25.91s/it]


In [84]:
X_tensor=torch.tensor(X_test_c)
predictions=model(X_tensor.float()).squeeze(1)
print(predictions)
label=torch.tensor(y_test)
for i in range(len(label)):
        if label[i]==1:
            label[i] = 0
        else:
            label[i]=1
print(label)
loss = criterion(predictions, label.float())
acc = binary_accuracy(predictions, label.float())
print('')
print('Accuracy:',acc)
print('')
print(loss)

tensor([5.2172e-03, 9.9299e-01, 9.9714e-01, 2.4885e-02, 3.4008e-03, 1.7592e-03,
        9.9949e-01, 3.8367e-03, 9.9953e-01, 9.9986e-01, 3.1252e-03, 8.2579e-02,
        9.9762e-01, 9.9997e-01, 3.1298e-03, 7.1565e-03, 9.9605e-01, 9.9876e-01,
        9.9963e-01, 1.4773e-03, 9.2540e-04], grad_fn=<SqueezeBackward1>)
tensor([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

Accuracy: tensor(1.)

tensor(26.4663, grad_fn=<DivBackward1>)
